### PR TITLE
Updated Sprint1.md and README.md

### LINKED ISSUE #35: Sprint1 Demo
## Description
As a project reviewer, I want to check the progress of the project at the end of the sprint.

I would like to see a demo of application and a documentation (Sprint1.md).

Sprint1.md should have points listing things delivered in planning, development, testing, and documentation phases of Sprints.

## Acceptance Criteria
- [x] Front End Video Demo 
- [x] Back End Video Demo
- [x] Add videos in repo
- [x] Sprint accomplishment documentation in Sprint1.md

### PR DESCRIPTION
**Pull request by haxxorsid**
## Acceptance Criteria
- [x] Sprint accomplishment documentation in Sprint1.md

### CODE REVIEW

**Review by shashank136 — APPROVED** [review]
Cool

**Review by bahetianjali — APPROVED** [review]
Seems good.

**Review by Vineetkhadloya — APPROVED** [review]
Okay 👍🏻

**Review by Vineetkhadloya — APPROVED** [review]
Okay 👍🏻

**Pull request merged**
