### PR TITLE
Update README.md, created Sprint4.md and updated postman collection

### LINKED ISSUE #99: Sprint4 Demo
## Description
As a project reviewer, I want to check the progress of the project at the end of the sprint.

I would like to see a demo of application and a documentation (Sprint4.md).

Sprint4.md should have points listing things delivered in planning, development, testing, and documentation phases of Sprints.

## Acceptance Criteria
- [x] Deploy app on web
- [x] Application Demo 
- [x] Cypress integration testing demo 
- [x] Back End unit testing Demo
- [x] Update wiki 
- [x] Sprint accomplishment documentation in Sprint4.md
- [x] Update README.md for project description, demo videos, Sprint4.md link

### LINKED ISSUE #102: Show verified ticks for posts by verified users
## Description
As a user, I want to see which users are actually verified to be working at the place they're working at in their respective posts. I would like to see a green tick beside their current position and company name if they are verified.

## Acceptance Criteria
- [x] Add verified green tick beside the current position and title displayed in the card in "post by others".
- [x] Add a tooltip to this green tick icon displaying "this user is verified".
- [x] Update postman collection

### PR DESCRIPTION
**Pull request by bahetianjali**
## Acceptance criteria for markdown (#99 ):
- [x] Sprint accomplishment documentation in Sprint4.md
- [x] Update README.md for project description, demo videos, Sprint4.md link

## Acceptance criteria for postman collection (#102 ):
- [x] Update postman collection

### CODE REVIEW

**Review by haxxorsid — DISMISSED** [review]
good to go.

**Review by Vineetkhadloya — DISMISSED** [review]
approved.

**Review by shashank136 — DISMISSED** [review]
Approved

**Review by shashank136 — APPROVED** [review]
Approved

**Review by Vineetkhadloya — APPROVED** [review]
Approved!

**Review by haxxorsid — APPROVED** [review]
Looks great!

**Pull request merged**
