### PR TITLE
Added Epic issue template and updated bug report template

### LINKED ISSUE #33: Setup Issue templates
## Description

As a developer, I need a way to automatically receive a standard format to create an user story or a bug.

I will be modifying this standard format with my own details (like description, acceptance criterias, steps to reproduce, etc...) and create an issue.

## Acceptance Criteria
- [x] Create an issue template for User story
- [x] Create an issue template for Bug
- [x] Create an issue template for Epic

### PR DESCRIPTION
**Pull request by haxxorsid**
## Acceptance criteria
- [x] Create an issue template for Bug
- [x] Create an issue template for Epic

### CODE REVIEW

**Review by bahetianjali — APPROVED** [review]

**Review by shashank136 — APPROVED** [review]
Approved

**Review by shashank136 — APPROVED** [review]
Approved

**Review by bahetianjali — APPROVED** [review]
Nice template

**Review by Vineetkhadloya — APPROVED** [review]
Looks good now !!

**Pull request merged**
