### PR TITLE
Create CI for Go Backend

### LINKED ISSUE #92: Add support for Golang Continuous integration
## Description
As a developer, I would like support for Continuous integration. This CI should be able to:

- Unit test cases
- go vet
- go staticcheck
- go lint
- dependencies
- build

## Acceptance Criteria
- [x] This pipeline should execute on every pull request created
- [x] This pipeline should be executed successfully then only PR should be merged
- [x] All scripts should pass successfully else specific step in pipeline should fail
- [x] Fix any existing lint, static check, build, dependencies errors in go code.

### PR DESCRIPTION
**Pull request by shashank136**
## Acceptance Criteria
- [x] This pipeline should execute on every pull request created
- [x] This pipeline should be executed successfully then only PR should be merged
- [x] All scripts should pass successfully else specific step in pipeline should fail
- [x] Fix any existing lint, static check, build, dependencies errors in go code.

### CODE REVIEW

**Review by haxxorsid — DISMISSED** [review]
Approved.

**Review by Vineetkhadloya — DISMISSED** [review]
Good

**Review by haxxorsid — APPROVED** [review]
Approved.

**Review by bahetianjali — APPROVED** [review]

**Review by bahetianjali — APPROVED** [review]

**Review by bahetianjali — APPROVED** [review]

**Review by Vineetkhadloya — APPROVED** [review]
Great! Finally a CI pipeline!

**Pull request merged**
