### PR TITLE
Added cypress integration tests

### LINKED ISSUE #100: Add or update cypress integration tests
## Description
As a developer/project reviewer, I would like to have some integration tests in place for create profile, home, edit profile pages mimicking user's behaivor and checking all the possible actions, visual elements, edge cases. 

## Acceptance Criteria
- [x] Add integration tests for create post.
- [x] Add integration tests for home (view posts by you, view posts by others).
- [x] Add integration tests for edit profile (profile, email, password).

### PR DESCRIPTION
**Pull request by bahetianjali**
## Acceptance criteria:
- [x] Add integration tests for home (view posts by you, view posts by others).
- [x] Add integration tests for edit profile (profile, email, password).

### CODE REVIEW

**Review by Vineetkhadloya — DISMISSED** [review]
this looks good to me. approving.

**Review by haxxorsid — DISMISSED** [review]
Looks good.

**Review by Vineetkhadloya — APPROVED** [review]
Approved

**Review by haxxorsid — APPROVED** [review]

**Review by shashank136 — APPROVED** [review]
Approved

**Pull request merged**
