### PR TITLE
Added Postman Collection, Sprint2.md, and updated README.md and Sprint1.md

### LINKED ISSUE #35: Sprint1 Demo
## Description
As a project reviewer, I want to check the progress of the project at the end of the sprint.

I would like to see a demo of application and a documentation (Sprint1.md).

Sprint1.md should have points listing things delivered in planning, development, testing, and documentation phases of Sprints.

## Acceptance Criteria
- [x] Front End Video Demo 
- [x] Back End Video Demo
- [x] Add videos in repo
- [x] Sprint accomplishment documentation in Sprint1.md

### LINKED ISSUE #54: Creating backend for Edit Profile
## Description
As a developer, I would like three different routes to update profile, update email, and update password. User would access these routes only when I am logged in.  For update email, I will pass my new email, update my current company according to that email as well. For update password, I would pass my current password as well as new password. 

I would like to see success and failure responses depending on the requests I have sent from the frontend. 

## Acceptance Criteria
- [x] Extract userId from the token in the cookie.
- [x] Update `/api/users/id` route to provide user details of the current logged in user.
- [x] Create a route `/api/users/id/updateprofile` to update user profile.
- [x] Create a route `/api/users/id/updateemail` to update user email.
- [x] Ensure the new email is unique and update CompanyId accordingly by adding additional checks for existing and non-existing company domain in `Company` table. 
- [x] Create a route `/api/users/id/updatepassword` to update user password.
- [x] Ensure current password matches with the password in the database, only then update it with the new password. 
- [x] Protect these 3 routes from unauthorized trigger.
- [x] Send appropriate success/error response if there are any issues in validation.
- [x] Create or Update Postman collection

### LINKED ISSUE #55: Creating backend for Home (Previous posts by you)
## Description

As a developer, I want to be able to fetch posts made by me previously. I will include my token as part of the cookie, token contains my userId. Use that userId to fetch all my posts from the `Posts` table.

Ensure, there is a required foreign key relationship in place between `Users` and `Posts` table.  Create a route `/api/posts/userid` which will fetch my posts and return the response back as a json. This route should be protected, as only user who is logged in can trigger it.

## Acceptance Criteria
- [x] Create a route `/api/posts/userid` to fetch posts by me.
- [x] Ensure there is a foreign key relationship between `Users` and `Posts` table.
- [x] Update `db/ create_table_users.sql` for any change in the `users` table.
- [x] Update `db/ create_table_posts` for any change in the `posts` table.
- [x] Extract userId from the token in the cookie.
- [x] Protect route `/api/posts/userid` from unauthorized trigger.
- [x]  Send appropriate success/error response if there are any issues in validation.
- [x] Create or Update Postman collection

### LINKED ISSUE #59: Creating backend for Register
## Description
As a developer, I want to be able to register. From frontend, the details user is sending are:
- First Name
- Last Name
- Current location
- Current position
- Current company
- Current school
- Years of experience (years_of_experience_id from YearsOfExperience table)
- Email (possible work email one of the inserted ones in Company table)
- Password

As a user, I should receive some validation like if a field is not provided or email is not a valid email. Ensure password is encrypted and stored in the database.

As a developer, you should set CompanyId based on work email provided by the user (match domains inserted in Company table) and similarly corresponding Company name from Company table should be set in User table instead of the one provided by the user.  In this case set a verified field as true in the user table.

As a developer, the company Id should be null if no matching company was found in Company Table based on work email provided, and assume Current company name provided by the user is correct. In this case set a verified field as false in the user table.

As a user, I should be able to see different years of experience dropdown in the registration form. So, please create an API to fetch years of experiences from YearsOfExperience table.

## Acceptance Criteria
- [x] Update AddUser api to register user (created at `/api/users/newuser`)
- [x] Ensure password is encrypted and stored in the database.
- [x] Handle condition where work email provided by the user matches with a domain found in Company table.
- [x] Handle condition where work email provided by the user doesn't match with any domain found in Company table.
- [x] Create API for fetching years of experiences to show in the frontend dropdown at `/api/experiences`
- [x] Update `db/ create_table_users.sql` for any change in the `users` table.
- [x] Add unit test cases
- [x] Create or Update postman collection.

### LINKED ISSUE #60: Create backend for login
## Description
As a user/developer, I want to login and logout. I should be able to access protected and unprotected APIs if I am unauthenticated.

I would like to have an API `/api/login` which will check if email and password were valid or not and if valid, set JWT cookie with 30 minutes expiry time (include userId in the token).

I would to have an API for logout at `/api/logout`.
I would like to have an API for validation at `/api/validatelogin`

I want my session to be maintained for minimum 30 minutes.

I will send email and passwords at `/api/login` API, I would like to have some validation at these APIs to receive success or error responses. All routes except `/api/login` and `/api/users/newuser` must be protected using validate login API (`/api/validatelogin`) so that only logged in users can call them.

## Acceptance Criteria
- [x] Create an API `/api/login` which will check if email and password were valid or not and if valid, set JWT cookie with 30 minutes expiry time.
- [x] Create an API `/api/logout` which will set cookie to 0 expiry time.
- [x] Create an API `/api/validatelogin` which will check if cookie in the request header is valid or present or not. 
- [x] Protect all routes with `api/validatelogin` except `/api/login` and `/api/users/newuser`.
- [x] Send appropriate success/error response if there are any issues in validation.
- [x] Create or Update Postman collection

### LINKED ISSUE #64: Sprint2 Demo
## Description
As a project reviewer, I want to check the progress of the project at the end of the sprint.

I would like to see a demo of application and a documentation (Sprint2.md).

Sprint2.md should have points listing things delivered in planning, development, testing, and documentation phases of Sprints.

## Acceptance Criteria
- [x] Front End Video Demo 
- [x] Back End Video Demo
- [x] Update wiki 
- [x] Upload videos on youtube and link them in Sprint2.md
- [x] Sprint accomplishment documentation in Sprint2.md

### PR DESCRIPTION
**Pull request by Vineetkhadloya**
## Acceptance Criteria for Postman collection
- [x] Create/update postman collection (#54, #55, #59, #60)

## Acceptance criteria for Sprint2.md
- [x] Sprint accomplishment documentation in Sprint2.md

## Acceptance criteria for Sprint1.md
- [x] Sprint accomplishment documentation in Sprint1.md

### CODE REVIEW

**Review by haxxorsid — DISMISSED** [review]
Approved!

**Review by bahetianjali — DISMISSED** [review]
Great work!

**Review by haxxorsid — APPROVED** [review]
Approved!

**Review by shashank136 — APPROVED** [review]
Approved

**Review by bahetianjali — APPROVED** [review]

**Pull request merged**
