### PR TITLE
Added backend unit test cases

### LINKED ISSUE #101: Add unit test cases for backend
## Description
As a developer and project reviewer, I would like to have backend unit test cases for login, logout, view posts by the current user and others, edit profile (profile, password, email), create post.

## Acceptance Criteria
- [x] Add tests for login, logout
- [x] Add tests for view posts by the user and others.
- [x] Add tests for creating posts
- [x] Add tests for edit profile (profile, password, email).

### PR DESCRIPTION
**Pull request by shashank136**
## Acceptance criteria
- [x] Add tests for login, logout
- [x] Add tests for view posts by the user and others.
- [x] Add tests for creating posts
- [x] Add tests for edit profile (profile, password, email).

### CODE REVIEW

**Comment by shashank136** [comment]
@haxxorsid looks like there is some issue with the in-memory DB configuration you created. Can you once check it?

**Comment by haxxorsid** [comment]
@shashank136 issue solved.

**Review by haxxorsid — APPROVED** [review]
Approved. Great work!

**Review by Vineetkhadloya — APPROVED** [review]
Approved!

**Review by bahetianjali — APPROVED** [review]
good work

**Pull request merged**
