### PR TITLE
Adding Dummy SQL Tables

### LINKED ISSUE #9: Create project boilerplate code (SQL)
As a developer, I want SQL code to be written in a folder “db”. 

Create a dummy table called “Cards” and add a dummy record. Create this table under schema “app”. 

Save the sql queries in the “db” folder.

## Acceptance Criteria
-	[x] Learn and setup Postgres SQL 14.1
-	[x] Write queries to create table and save these queries in “db” folder

### PR DESCRIPTION
**Pull request by Vineetkhadloya**
-	[x] Learn and setup Postgres SQL 14.1
-	[x] Write queries to create table and save these queries in “db” folder

### CODE REVIEW

**Review by shashank136 — COMMENTED** [review]
looks ok to me. Can be pushed. Please, validate the DB after the update.

**Review by haxxorsid — APPROVED** [review]
looks good, will adjust boilerplate backend accordingly. please review and approve @bahetianjali  @shashank136 .

**Review by shashank136 — APPROVED** [review]
Looks good to me. Please, push the code

**Comment by bahetianjali** [comment]
This is good.

**Review by bahetianjali — APPROVED** [review]

**Pull request merged**
