### PR TITLE
Mentioned backend, frontend with member names in README.md

### LINKED ISSUE #78: Sprint3 Demo
## Description
As a project reviewer, I want to check the progress of the project at the end of the sprint.

I would like to see a demo of application and a documentation (Sprint3.md).

Sprint3.md should have points listing things delivered in planning, development, testing, and documentation phases of Sprints.

## Acceptance Criteria
- [x] Front End Video Demo 
- [x] Back End Video Demo
- [x] Update wiki 
- [x] Upload videos on youtube and link them in Sprint3.md
- [x] Sprint accomplishment documentation in Sprint3.md

### PR DESCRIPTION
**Pull request by Vineetkhadloya**
# Acceptance critera
- [x] Update wiki

### CODE REVIEW

**Review by haxxorsid — APPROVED** [review]
Approved.

**Review by bahetianjali — CHANGES_REQUESTED** [review]
Seems good.

**Review by shashank136 — APPROVED** [review]
Approved

**Review by bahetianjali — APPROVED** [review]
Seems fine

**Pull request merged**
