### PR TITLE
Sprint3 Demo

### LINKED ISSUE #78: Sprint3 Demo
## Description
As a project reviewer, I want to check the progress of the project at the end of the sprint.

I would like to see a demo of application and a documentation (Sprint3.md).

Sprint3.md should have points listing things delivered in planning, development, testing, and documentation phases of Sprints.

## Acceptance Criteria
- [x] Front End Video Demo 
- [x] Back End Video Demo
- [x] Update wiki 
- [x] Upload videos on youtube and link them in Sprint3.md
- [x] Sprint accomplishment documentation in Sprint3.md

### PR DESCRIPTION
**Pull request by Vineetkhadloya**
## Acceptance Criteria
- [x] Sprint accomplishment documentation in Sprint3.md

### CODE REVIEW

**Review by shashank136 — DISMISSED** [review]
looks good

**Review by haxxorsid — APPROVED** [review]
Perfect

**Review by shashank136 — APPROVED** [review]
Approved

**Review by bahetianjali — APPROVED** [review]
Looks good

**Pull request merged**
