### PR TITLE
Added cypress integration tests

### LINKED ISSUE #53: Updating frontend for Home (previous posts by you)
## Description
As a user, I would like to see posts created by me previously and others for my organization in home. 

I would like to have two tabs in Home "By you" and "By others for your company". I do not need "Requests" page in the Navbar anymore for a separate page to show posts "By others for your company".

If I click on "By you" tab, I would like to see a card with my target position and target company name as a title with a delete button (Red colored in an icon) on it's right, this delete button should call `api/posts/id/{post_Id}` where replace post_id with actual post id . Below, I would like to see  "Message from You" and "Posted At" in light colors.

In the bottom of the card, I want to see the buttons which will redirect me to my resume link and job link.

Fetch these posts from an API at `\api\posts`.

If I click on "By others for your company", I would like to see posts made by referee's for looking for job at my organization. I would like to see referee's current company name and current position as the title in the card. I do not wish to see the delete button. Below this in the card, I would like to see name, email, school, current location, target company name, target position, school, posted at. In the bottom of the card, I want to see the buttons which will redirect me to the resume link and job link. There should be a down/up arrow which will show and hide message from the candidate to the referrer.  For now, do not fetch any posts for these cards.

## Acceptance criteria
- [x] Created two tabs "By you" and "By others for your company"
- [x] Delete Requests page in the navbar
- [x] Fetch posts by me if I click on "By you" tab.
- [x] Show cards for posts by me
- [x] Show cards for posts by other for my organization. (Show no posts for "By others for your company" for now)
- [x] For posts by me, show a delete button. This delete button should call delete posts API at `api/posts/id/{post_id}`.
- [x] For resume link and job link, show two buttons which will redirect me to resume and job links.
- [x] For "By others for your company" cards, make a up and down slider work for "message from the candidate"
- [x] Write integration tests in cypress for Navbar.

### LINKED ISSUE #56: Updating Front-End for Login
## Description
As a developer, I want the login page to send user credentials to Back-End for verification of the user.

I want this input fields to be seen in the form:
- Email (string, validation=required, isEmail)
- Password (string, hidden, validation=required)

This fields should be sent to backend at `/api/login` endpoint.

I want fields to be highlighted with error if required field is not supplied or email is not an valid email.
I want the user to be redirected to home page if success response from login endpoint.

## Acceptance Criteria
- [x] Should show validation errors for the fields as specified in the description.
- [x] Should show error message in toast on response from API.
- [x] Should show success message in toast
- [x] The form values should be sent to `/api/login` endpoint.
- [x] Redirect the user to home page if success.
- [x] Write integration tests in cypress

### LINKED ISSUE #58: Updating Front-End for Register
## Description
As a user, in order to use the services offered by the referral board, I want to be able to successfully able to register at the website. For the purpose of registering, I want to be able to send the data to the backend so that I can log in and use the features offered. 

I want this input fields to be seen in the form:
- First name (string, validation=required)
- Last name (string, validation=required)
- Current location (string, validation=required)
- Current school (string, validation=required)
- Current position (string, validation=required)
- Current company name (string, validation=required)
- Years of experience (a dropdown which shows experiences from `/api//experiences` API) ( number, default=1)
- Email (string, validation=required, isEmail)
- Password (string, hidden, validation=required)

This fields should be sent to backend at `/api/users/newuser` endpoint.

I want fields to be highlighted with error if required field is not supplied or email is not an valid email.

I want to see a toast error message if email is already registered or there is some server error registering the user.

I want to see a toast success message if user was registered successful.

## Acceptance Criteria
- [x] Should show validation errors for the fields as specified in the description.
- [x] Should show error message in toast on response from API.
- [x] Should show success message in toast
- [x] Should fetch years of experience dropdown from '/api/experiences' endpoint.
- [x] The form values should be sent to `/api/users/experiences/ endpoint.
- [x] Write integration tests in cypress.
- [x] Add frontend unit test cases

### PR DESCRIPTION
**Pull request by bahetianjali**
## Acceptance criteria for navbar tests (from #53)
- [x] Write integration tests in cypress for Navbar.

## Acceptance criteria for login tests (from #56)
- [x] Write integration tests in cypress.

## Acceptance criteria for register tests (from #58)
- [x] Write integration tests in cypress.

### CODE REVIEW

**Review by shashank136 — DISMISSED** [review]
Approved

**Review by haxxorsid — APPROVED** [review]
Approved

**Review by shashank136 — APPROVED** [review]
Looks clean. Please, submit

**Review by Vineetkhadloya — APPROVED** [review]
Good Work !!

**Pull request merged**
